#!/usr/bin/env python3
"""
Build the Firefox (Gecko) variant of the extension from the Chrome source.

Run it from the repo root:

    python3 build-firefox.py

Output:
    dist/firefox/                 unpacked, ready to load in Firefox
    dist/4xs-toolbox-firefox-<version>.zip

Nothing in the Chrome source is modified, and no source file is duplicated in
the repo - the Firefox build is generated, so a change to background.js or the
catalog only has to be made once. Re-run this after every Chrome-side change.

Why a separate build at all (three Gecko incompatibilities):

  1. Background context. Chrome MV3 requires "background.service_worker";
     Firefox does not implement service-worker backgrounds and wants
     "background.scripts" (an event page) instead.

  2. Promises vs. callbacks. In Firefox, browser.* returns promises while
     chrome.* is the Chrome-compatible callback flavour. background.js awaits
     seven API calls, and `await chrome.tabs.query(...)` would resolve to
     undefined there and throw on the following for-of. Those call sites are
     rewritten onto a `geckoApi` alias that prefers browser.*. Every other file
     uses Chrome-style callbacks plus runtime.lastError, which Firefox's chrome.*
     namespace supports as-is, so they are copied verbatim.

  3. Add-on identity. Gecko needs an explicit ID to sign and update against,
     and a strict_min_version. 127.0 is deliberate: before Firefox 127, MV3
     host permissions (including content_scripts match patterns) were NOT
     granted at install and the user had to opt in per-site, which would have
     left badges silently missing on a fresh install. From 127 they are shown
     in the install prompt and granted up front.
"""

import json
import os
import re
import shutil
import zipfile

# DELIBERATE FRESH START (Pavel, 2026-09-05). This does NOT match the old
# AMO listing's id (axis-msrp-price-overlay@camstreamer.local), so v5.0 is
# submitted to AMO as a NEW add-on rather than an update - he does not want
# "camstreamer" or "axis" embedded in this product's identity. Consequences
# accepted: new listing URL, installs/reviews start at zero, and users of
# the old listing are not migrated automatically.
# Do not "correct" this back to the old id.
GECKO_ID = "4xs-toolbox@4xs.dev"
# 128 is the first release that supports "optional_host_permissions", which the
# manifest uses for the IP-scanner subnet grant. 127 linted with a warning.
STRICT_MIN_VERSION = "128.0"

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(ROOT, "dist", "firefox")

# Copied byte-for-byte: Chrome-style callbacks and runtime.lastError both work
# on Firefox's chrome.* namespace, so these need no changes at all.
VERBATIM = [
    "i18n.js",
    "catalog-data.js",
    "chipset-data.js",
    "fov-data.js",
    "axis-map.js",
    "content.js",
    "content.css",
    "search-content.js",
    "search-content.css",
    "products-content.js",
    "products-content.css",
    "popup.html",
    "popup.js",
    "options.html",
    "options.js",
    "fov-map.html",
    "fov-map.css",
    "fov-map.js",
    "find-cams.html",
    "find-cams.js",
    "find-cams.css",
    "find-cams-page.js",
]
VERBATIM_DIRS = ["icons", "vendor"]

GECKO_SHIM = """// --- Firefox build shim (generated by build-firefox.py - do not edit here) ---
// Firefox exposes two namespaces: browser.* is promise-based, chrome.* is the
// Chrome-compatible callback flavour. The awaited calls in this file need
// promises, so they go through geckoApi; the addListener calls below are
// identical in both namespaces and are left on chrome.* to keep the diff
// against the Chrome source as small as possible.
const geckoApi = (typeof browser !== "undefined") ? browser : chrome;

"""


def build_manifest():
    with open(os.path.join(ROOT, "manifest.json"), encoding="utf-8") as fh:
        m = json.load(fh)

    # Firefox has no service-worker background; use an event page instead.
    m["background"] = {"scripts": ["background.js"]}

    m["browser_specific_settings"] = {
        "gecko": {
            "id": GECKO_ID,
            "strict_min_version": STRICT_MIN_VERSION,
            # AMO requires this key on every new extension. Nothing is
            # transmitted anywhere: the price list stays in chrome.storage,
            # the subnet scan never leaves the machine, and the only outbound
            # requests are to axis.com, camstreamer.com, the tile/FX/geo-IP
            # services - none of them carry user data to the developer.
            "data_collection_permissions": {"required": ["none"]},
        }
    }
    return m


def build_background():
    with open(os.path.join(ROOT, "background.js"), encoding="utf-8") as fh:
        src = fh.read()

    # Only the awaited call sites need the promise-based namespace.
    patched, n = re.subn(r"await chrome\.", "await geckoApi.", src)
    if n == 0:
        raise SystemExit("build-firefox: found no 'await chrome.' call sites - has background.js changed?")

    # Sanity check: nothing awaited may still be on the callback namespace.
    leftover = re.findall(r"await chrome\.[a-zA-Z.]*", patched)
    if leftover:
        raise SystemExit("build-firefox: un-patched awaited call(s): %s" % leftover)

    return GECKO_SHIM + patched, n


def main():
    if os.path.isdir(OUT_DIR):
        shutil.rmtree(OUT_DIR)
    os.makedirs(OUT_DIR)

    manifest = build_manifest()
    with open(os.path.join(OUT_DIR, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    background, patched_count = build_background()
    with open(os.path.join(OUT_DIR, "background.js"), "w", encoding="utf-8") as fh:
        fh.write(background)

    for name in VERBATIM:
        shutil.copy2(os.path.join(ROOT, name), os.path.join(OUT_DIR, name))
    for name in VERBATIM_DIRS:
        shutil.copytree(os.path.join(ROOT, name), os.path.join(OUT_DIR, name))

    # Every file the manifest points at must actually exist in the output.
    referenced = set()
    for entry in manifest.get("content_scripts", []):
        referenced.update(entry.get("js", []))
        referenced.update(entry.get("css", []))
    referenced.update(manifest["background"]["scripts"])
    referenced.add(manifest["action"]["default_popup"])
    referenced.add(manifest["options_ui"]["page"])
    referenced.update(manifest["icons"].values())
    referenced.update(manifest["action"]["default_icon"].values())
    missing = [r for r in sorted(referenced) if not os.path.exists(os.path.join(OUT_DIR, r))]
    if missing:
        raise SystemExit("build-firefox: manifest references missing file(s): %s" % missing)

    version = manifest["version"]
    zip_path = os.path.join(ROOT, "dist", "4xs-toolbox-firefox-%s.zip" % version)
    if os.path.exists(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for folder, _dirs, files in os.walk(OUT_DIR):
            for f in sorted(files):
                full = os.path.join(folder, f)
                zf.write(full, os.path.relpath(full, OUT_DIR))

    size_kb = os.path.getsize(zip_path) // 1024
    print("Firefox build v%s" % version)
    print("  unpacked : %s" % os.path.relpath(OUT_DIR, ROOT))
    print("  zip      : %s (%d KB)" % (os.path.relpath(zip_path, ROOT), size_kb))
    print("  patched  : %d awaited call site(s) onto browser.*" % patched_count)
    print("  gecko id : %s (min Firefox %s)" % (GECKO_ID, STRICT_MIN_VERSION))


if __name__ == "__main__":
    main()
